---
# tasks file for ansible-ntp

- name: remove ntp
  yum: name=ntp state=absent

- name: install openntp
  yum: name=openntp state=present

- name: start and enable ntpd
  service: name=openntpd state=started enabled=yes

